from .abstract_bci_task import AbstractBCITask
from .left_hand_right_hand_feet_tongue_mi_task import LeftHandvRightHandvFeetvTongueMITask
from .left_hand_right_hand_mi_task import LeftHandvRightHandMITask
from .right_hand_feet_mi_task import RightHandvFeetMITask
from .five_fingers_mi_task import FiveFingersMITask
from .minitask import bcicompiv2a
from .bci_iv_2b import bcicompiv2b
from .weibo2014 import weibo2014
from .cho2017 import cho2017
from .bci_iv_2a_4class import bcicompiv2a_4class
from .schirrmeister2017 import schirrmeister2017
from .physionetmi import physionetmi
from .zhou2016 import zhou2016
from .barachant2012_base import barachant2012_base
from .faller2012_base import faller2012_base
from .physionetmi_base import PhysionetMIBaseTask
from .scherer2015_base import scherer2015
from .schirrmeister2017_base import schirrmeister2017_base
from .weibo2014_base import weibo2014_base