from .abstract_bci_task import AbstractBCITask
from .left_hand_right_hand_feet_tongue_mi_task import LeftHandvRightHandvFeetvTongueMITask
from .left_hand_right_hand_mi_task import LeftHandvRightHandMITask
from .right_hand_feet_mi_task import RightHandvFeetMITask
from .five_fingers_mi_task import FiveFingersMITask
from .minitask import bcicompiv2a
from .bci_iv_2b import bcicompiv2b
from .weibo2014 import weibo2014
from .cho2017 import cho2017
from .bci_iv_2a_4class import bcicompiv2a_4class
from .schirrmeister2017 import schirrmeister2017
from .physionetmi import physionetmi
from .zhou2016 import zhou2016